/**
 * deploy.ts — Night Markets Escrow Contract Deployment
 * midnight-js 3.0.0 · Compact 0.28.0 · Preprod
 *
 * Pre-flight checklist:
 *   1. Proof server:  npm run proof-server   (docker — separate terminal)
 *   2. Funded wallet: tNight from https://midnight.network/faucet (unshielded address)
 *   3. DUST tokens:   register NIGHT UTXOs in Lace, wait for non-zero DUST balance
 *   4. Compiled:      npm run compile
 *
 * Run:
 *   npm run deploy
 *
 * Output:
 *   CONTRACT_ADDRESS=mn1_contract_preprod_...
 *   → paste into night-markets-v12.html: var NM_CONTRACT_ADDRESS = '...'
 */

import path                           from 'path';
import { indexerPublicDataProvider }  from '@midnight-ntwrk/midnight-js-indexer-public-data-provider';
import { httpClientProofProvider }    from '@midnight-ntwrk/midnight-js-http-client-proof-provider';
import { NodeZkConfigProvider }       from '@midnight-ntwrk/midnight-js-node-zk-config-provider';
import { MidnightProvider }           from '@midnight-ntwrk/midnight-js-types';
import { getLedgerNetworkId }         from '@midnight-ntwrk/midnight-js-network-id';
// 3.0.0: lowercase function, takes { privateStateStoreName, walletProvider }
import { levelPrivateStateProvider }  from '@midnight-ntwrk/midnight-js-level-private-state-provider';
import { WalletProvider, Wallet }     from '@midnight-ntwrk/wallet';
import * as Rx                        from 'rxjs';
import {
  CompiledContract,
  deployContract,
  submitCallTx,
  Providers,
} from '@midnight-ntwrk/compact-js';

// Contract bindings — generated by: npm run compile
// .js imports (not .cjs) — midnight-js 3.0.0 breaking change
import * as NightMarketsEscrow from '../contracts/managed/night-markets-escrow/contract/index.js';

// ── Network config ─────────────────────────────────────────────
// networkId: string literal in 3.0.0 (was enum in 2.x)
const NETWORK_ID      = 'preprod' as const;
const PROOF_SERVER    = 'http://localhost:6300';
const INDEXER_URI     = 'https://indexer.preprod.midnight.network';
const NODE_URI        = 'https://rpc.preprod.midnight.network';
const ZK_CONFIG_PATH  = path.resolve('./contracts/managed/night-markets-escrow');

// ── Provider types ─────────────────────────────────────────────
// All six providers required by deployContract() / submitCallTx()
// Source: Testnet to Preview migration guide
export interface NightMarketsProviders extends Providers {
  walletProvider:       WalletProvider;
  midnightProvider:     MidnightProvider;
  publicDataProvider:   ReturnType<typeof indexerPublicDataProvider>;
  privateStateProvider: ReturnType<typeof levelPrivateStateProvider>;
  proofProvider:        ReturnType<typeof httpClientProofProvider>;
  zkConfigProvider:     NodeZkConfigProvider;
}

interface PrivateState {
  escrowState?: { secretKey?: Uint8Array; };
}

// ── Main ───────────────────────────────────────────────────────
async function main() {
  console.log('🌙 Night Markets — Escrow Contract Deployment');
  console.log('━'.repeat(52));
  console.log('Network:      ', NETWORK_ID);
  console.log('Indexer:      ', INDEXER_URI);
  console.log('Proof server: ', PROOF_SERVER);
  console.log('ZK config:    ', ZK_CONFIG_PATH);
  console.log('');

  console.log('⚙️  Building providers...');
  const providers = await buildProviders();
  console.log('✓ All six providers ready\n');

  console.log('📦 Loading compiled contract + ZK keys...');
  const compiledContract = CompiledContract
    .make('night-markets-escrow', NightMarketsEscrow.Contract)
    .pipe(
      CompiledContract.withVacantWitnesses,
      CompiledContract.withCompiledFileAssets(ZK_CONFIG_PATH),
    );
  console.log('✓ Contract loaded\n');

  console.log('🚀 Deploying... (30–60s while ZK proofs are generated)');
  const deployed = await deployContract(providers, {
    compiledContract,
    privateStateId:      'escrowState',
    initialPrivateState: {} as PrivateState,
  });

  const contractAddress = deployed.deployTxData.public.contractAddress;

  console.log('');
  console.log('✅ Deployed!');
  console.log('━'.repeat(52));
  console.log('CONTRACT_ADDRESS=' + contractAddress);
  console.log('━'.repeat(52));
  console.log('');
  console.log('Next steps:');
  console.log('  1. Open night-markets-v12.html');
  console.log('  2. Set: var NM_CONTRACT_ADDRESS = \'' + contractAddress + '\'');
  console.log('  3. Replace simulateCompact*() with callTx helpers in this file');
  console.log('  4. npx serve . -p 3000 → open localhost:3000 in Chrome with Lace');
  console.log('  5. Post in #showcase on Midnight Discord 🌙');

  return { deployed, contractAddress, providers };
}

// ══════════════════════════════════════════════════════════════
// buildProviders — all six required by Testnet to Preview migration
// ══════════════════════════════════════════════════════════════
async function buildProviders(): Promise<NightMarketsProviders> {

  // 1. zkConfigProvider — loads proving/verifying keys from compiled output
  const zkConfigProvider = new NodeZkConfigProvider(ZK_CONFIG_PATH);

  // 2. proofProvider — confirmed: httpClientProofProvider(proofServerUri, zkConfigProvider)
  const proofProvider = httpClientProofProvider(PROOF_SERVER, zkConfigProvider);

  // 3. publicDataProvider — confirmed: indexerPublicDataProvider(indexerUri, indexerWsUri)
  const INDEXER_WS_URI = INDEXER_URI.replace('https://', 'wss://');
  const publicDataProvider = indexerPublicDataProvider(INDEXER_URI, INDEXER_WS_URI);

  // 4. walletProvider — needed before privateStateProvider (passed in as arg)
  const walletProvider = await openWalletProvider();

  // 5. privateStateProvider — 3.0.0: lowercase function, takes walletProvider
  //    NOT LevelPrivateStateProvider.open() — that was the 2.x class-based API
  const privateStateProvider = levelPrivateStateProvider({
    privateStateStoreName: 'night-markets-state',
    walletProvider,        // walletProvider passed in — confirmed 3.0.0 pattern
  });

  // 6. midnightProvider — Midnight node RPC connection
  const midnightProvider: MidnightProvider = {
    networkId: getLedgerNetworkId(NETWORK_ID),
    nodeUri:   NODE_URI,
  };

  return {
    walletProvider,
    midnightProvider,
    publicDataProvider,
    privateStateProvider,
    proofProvider,
    zkConfigProvider,
  };
}

// ── Wallet from seed phrase ────────────────────────────────────
// For local deployment. Set WALLET_SEED in a .env file (never commit).
// For Lace-connected checkout flow in the browser, walletProvider is
// provided by the DApp Connector — see connectLace() in night-markets-v12.html.
async function openWalletProvider(): Promise<WalletProvider> {
  const seed = process.env.WALLET_SEED;
  if (!seed) {
    throw new Error(
      'WALLET_SEED not set.\n\n'
      + 'Create a .env file:\n'
      + '  WALLET_SEED=word1 word2 word3 ... word24\n\n'
      + 'This wallet must have tNight and DUST on Preprod.\n'
      + 'Faucet: https://midnight.network/faucet'
    );
  }

  const walletCtx = await Wallet.open({
    seed,
    networkId: NETWORK_ID,
    nodeUri:   NODE_URI,
  });

  // DUST guard — confirmed pattern from deployment docs:
  // wallet.state() observable, filter isSynced + dust.walletBalance > 0n
  console.log('  Waiting for wallet sync + non-zero DUST balance...');
  await new Promise<void>((resolve, reject) => {
    const sub = walletCtx.wallet.state().pipe(
      Rx.filter((s: any) => s.isSynced),
      Rx.filter((s: any) => s.dust.walletBalance(new Date()) > 0n),
      Rx.take(1),
    ).subscribe({
      next:  ()    => { sub.unsubscribe(); resolve(); },
      error: (err) => { sub.unsubscribe(); reject(err); },
    });

    // Timeout after 60s with a helpful error
    setTimeout(() => {
      sub.unsubscribe();
      reject(new Error(
        'Timed out waiting for DUST balance.\n'
        + 'In Lace: register your NIGHT UTXOs for DUST generation\n'
        + 'and wait until DUST balance is non-zero before deploying.'
      ));
    }, 60_000);
  });
  console.log('  ✓ Wallet synced with non-zero DUST balance');

  return walletCtx.wallet.asProvider();
}

// ══════════════════════════════════════════════════════════════
// submitCallTx helpers — replace simulateCompact*() functions
// in night-markets-v12.html once CONTRACT_ADDRESS is deployed.
// All return Promise<void> — 3.0.0: all contract calls are async.
// ══════════════════════════════════════════════════════════════

/** createListing: seller posts listing with private IPFS metadata */
export async function callCreateListing(
  providers:     NightMarketsProviders,
  deployed:      Awaited<ReturnType<typeof deployContract>>,
  listingCid:    string,       // Opaque<"string"> IPFS CID
  sellerPkBytes: Uint8Array,   // disclose(sellerPk(localSecretKey()))
): Promise<void> {
  await submitCallTx(providers, {
    contract: deployed,
    circuit:  'createListing',
    args:     [listingCid, sellerPkBytes],
  });
}

/** fundEscrow: buyer funds the purchase */
export async function callFundEscrow(
  providers:    NightMarketsProviders,
  deployed:     Awaited<ReturnType<typeof deployContract>>,
  buyerPkBytes: Uint8Array,   // disclose(buyerPk(localSecretKey()))
  amountMicro:  bigint,       // NIGHT amount × 1_000_000n
): Promise<void> {
  await submitCallTx(providers, {
    contract: deployed,
    circuit:  'fundEscrow',
    args:     [buyerPkBytes, amountMicro],
  });
}

/** releaseEscrow: buyer confirms goods received — triggers round.increment(1) */
export async function callReleaseEscrow(
  providers: NightMarketsProviders,
  deployed:  Awaited<ReturnType<typeof deployContract>>,
): Promise<void> {
  await submitCallTx(providers, {
    contract: deployed,
    circuit:  'releaseEscrow',
    args:     [],
  });
}

/** disputeEscrow: seller raises a dispute */
export async function callDisputeEscrow(
  providers: NightMarketsProviders,
  deployed:  Awaited<ReturnType<typeof deployContract>>,
): Promise<void> {
  await submitCallTx(providers, {
    contract: deployed,
    circuit:  'disputeEscrow',
    args:     [],
  });
}

main().catch(console.error);
